### ISSUE TITLE
Feature Request: Document or add capability to utilize snowflake key pair authorization

### ISSUE THREAD

**Issue by brandocomando** [gooddata/gooddata-python-sdk#723]
Not sure if this this something that can already be done, from the docs it wasn't clear. 
But I want to add a datasource for snowflake that uses a ssh key pair instead of basic auth. I can see from the docs this is doable (and have done it) with the raw API. but it wasn't easy to understand how this would be done or added in the sdk.

**Comment by hkad98** [comment]
Hello @brandocomando, 

Thanks for your issue. Key-pair authentication for Snowflake is a new feature we haven't been able to reflect in the Python SDK yet. Adding this type of authentication to a data source entity might not be straightforward for someone not familiar with the Python SDK codebase. I am going to prioritize it. If you wish to contribute to Python SDK, feel free to have a look at [CatalogDeclarativeDataSource](https://github.com/hkad98/gooddata-python-sdk/blob/7668ff59cffc0c45614924b8136dbef70cbc1d04/gooddata-sdk/gooddata_sdk/catalog/data_source/declarative_model/data_source.py#L94-L94). It should be straightforward to add support for key-pair authentication there.

**Comment by hkad98** [comment]
@brandocomando PR adding an option to use key-pair auth just merged. It is going to be part of Thursday's release.
